### ISSUE TITLE
[🐛BUG] 打包后提示缺少SDK.DLL

### ISSUE THREAD

**Issue by 404forever1** [lich0821/WeChatFerry#276] opened 2024-11-19 07:43 UTC
![image](https://github.com/user-attachments/assets/a73dc3d8-6a49-43d4-825c-9131e3c55f24)

**Comment by lich0821** [comment] 2024-11-19 07:48
Closing this as a duplicate of #275

**Closed by lich0821** 2024-11-19 07:48 UTC
Labels: help wanted
